# application config
webhooks:
  logfile: output.log
  bindings:
    - id: my-custom-name
      token: 239423949234
      commands:
        - name: hello:world
          handler: App\Command\TestCommand::handleRequest
        - name: hello:world
          handler: App\Command\TestCommand::handleRequest